# Generated by Django 4.1.7 on 2023-03-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=250)),
                ("skill_set", models.CharField(max_length=500)),
            ],
        ),
    ]
